default_roles:
  - system
  - dotfiles
  - alacritty
  - bat
  - delta
  # # - discord
  # - docker
  - fd
  - firefox
  - fonts
  # - git
  - go
  # - hyprland
  # - julia
  # - lua
  # - miniconda
  - neofetch
  - neovim
  # - npm
  # - nvm
  - python
  - r
  # # - rofi
  - tmux
  # - tmuxp
  # # - waybar
  - zathura
  - zsh

git_user_name: "zenoix"
git_user_email: "41812358+zenoix@users.noreply.github.com"
