---
- name: Clean Up Downloaded Go Tar
  ansible.builtin.file:
    path: "/tmp/{{ go_file }}.tar.gz"
    state: absent
  become: true

- name: Remove Extracted Go Directory
  ansible.builtin.file:
    path: /tmp/go
    state: absent
  become: true
