---
- name: "LibreOffice | Checking for Distribution Config | {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: libreoffice_distribution_config

- name: "LibreOffice | Run Tasks | {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: libreoffice_distribution_config.stat.exists
