---
- name: "System | Update Package Manager | {{ ansible_distribution }}"
  community.general.pacman:
    update_cache: true
    upgrade: true
    state: latest
  become: true

- name: "System | Install Packages | {{ ansible_distribution }}"
  community.general.pacman:
    name:
      - git
  become: true
