---
- name: "Zsh | Checking for Distribution Config | {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: zsh_distribution_config

- name: "Zsh | Run Tasks | {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: zsh_distribution_config.stat.exists

- name: "Zsh | Change Default Shell"
  block:
    - name: "Find Zsh Binary"
      ansible.builtin.command:
        cmd: which zsh
      register: zsh_bin_path
      changed_when: zsh_bin_path.rc != 0

    - name: "Change Default Shell"
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: "{{ zsh_bin_path.stdout }}"
      become: true

- name: "Zsh | Plugins | Checking for Distribution Config | {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}_plugins.yaml"
  register: zsh_plugins_distribution_config

- name: "Zsh | Plugins | Run Tasks | {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}_plugins.yaml"
  when: zsh_plugins_distribution_config.stat.exists
