---
- name: "Zsh | Plugins | Install fzf | {{ ansible_distribution }}"
  block:
    - name: "Zsh | Plugins | Clone fzf"
      ansible.builtin.git:
        repo: "https://github.com/junegunn/fzf.git"
        dest: ~/.fzf/
        depth: 1
        version: master
      become: true

    - name: "Zsh | Plugins | Install fzf"
      ansible.builtin.command:
        cmd: ~/.fzf/install
      register: fzf_install
      changed_when: fzf_install.rc != 0

- name: "Zsh | Plugins | Install fzf-git | {{ ansible_distribution }}"
  ansible.builtin.git:
    repo: "https://github.com/junegunn/fzf-git.sh.git"
    dest: /usr/share/zsh/plugins/fzf-git.sh/
    version: main
  become: true

- name: "Zsh | Plugins | Install zsh-syntax-highlighting | {{ ansible_distribution }}"
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: /usr/share/zsh/plugins/zsh-syntax-highlighting/
    version: master
  become: true

- name: "Zsh | Plugins | Install zsh-autosuggestions | {{ ansible_distribution }}"
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: /usr/share/zsh/plugins/zsh-autosuggestions/
    version: master
  become: true

- name: "Zsh | Plugins | Install zoxide | {{ ansible_distribution }}"
  block:
    - name: "Zsh | Plugins | Download zoxide"
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh
        dest: /tmp/zoxide.sh
        mode: "0755"
    - name: "Zsh | Plugins | Install zoxide"
      ansible.builtin.shell:
        cmd: set -o pipefail && cat /tmp/zoxide.sh | sh -s -- -y
      register: zoxide_install
      changed_when: zoxide_install.rc != 0
