---
- name: Golang | Define GOARCH | Archlinux
  ansible.builtin.set_fact:
    goarch: "{{ ansible_machine | replace('x86_64', 'amd64') | replace('aarch64', 'arm64') }}"

- name: Golang | Define GOOS | Archlinux
  ansible.builtin.set_fact:
    goos: "{{ ansible_system | lower }}"

- name: Golang | GOARCH Value | Archlinux
  ansible.builtin.debug:
    var: goarch

- name: Golang | GOOS Value | Archlinux
  ansible.builtin.debug:
    var: goos

- name: Golang | Getting version information | Archlinux
  ansible.builtin.command: "/usr/bin/go version"
  register: current_go_version
  changed_when: false
  failed_when: false

- name: Golang | Querying Latest Version JSON | Archlinux
  ansible.builtin.uri:
    url: https://go.dev/dl/?mode=json
  register: go_latest_version_json
  changed_when: false

- name: Golang | Registering go Latest Version | Archlinux
  ansible.builtin.set_fact:
    go_latest_version: "go version {{ go_latest_version_json.json[0].version }} {{ goos }}/{{ goarch }}"

- name: Golang | Registering go Latest Release | Archlinux
  ansible.builtin.set_fact:
    go_latest_release: "{{ go_latest_version_json.json[0].version }}"

- name: Golang | Show current_go_version debug | Archlinux
  ansible.builtin.debug:
    var: current_go_version.stdout|default('')

- name: Golang | Show go_latest_release debug | Archlinux
  ansible.builtin.debug:
    var: go_latest_release

- name: Golang | Install Go | Archlinux
  community.general.pacman:
    name: go
    state: present
  become: true
