---
- name: Run Arch Tasks
  ansible.builtin.import_tasks: arch.yaml
  when: ansible_os_family == "Archlinux"

- name: Run Ubuntu Tasks
  ansible.builtin.import_tasks: ubuntu.yaml
  when: ansible_os_family == "Debian"
