---
- name: "Zathura | Checking for Distribution Config | {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: zathura_distribution_config

- name: "Zathura | Run Tasks | {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: zathura_distribution_config.stat.exists
