---
- name: "Tmux | Checking for Distribution Config | {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: tmux_distribution_config

- name: "Tmux | Run Tasks | {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: tmux_distribution_config.stat.exists

- name: "Tmux | Install TPM"
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "/home/{{ host_user }}/.tmux/plugins/tpm"
    version: master
