---
- name: "Alacritty | Checking for Distribution Config | {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: alacritty_distribution_config

- name: "Alacritty | Run Tasks | {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: alacritty_distribution_config.stat.exists

