---
- name: "Syncthing | Install Syncthing | {{ ansible_distribution }}"
  community.general.pacman:
    name:
      - syncthing
    state: present
  become: true

- name: "Syncthing | Enable Syncthing on User Login | {{ ansible_distribution }}"
  ansible.builtin.systemd_service:
    name: syncthing.service
    enabled: true
    scope: user
    state: started

