---
- name: "Neovim | Checking for Distribution Config | {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: neovim_distribution_config

- name: "Neovim | Run Tasks | {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: neovim_distribution_config.stat.exists
