name: Ansible Lint
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".github/**/*"
  pull_request:
    branches:
      - main
      - "README.md"
      - ".github/**/*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ansible-lint
        run: pip install ansible-lint

      - name: Install Galaxy Modules
        run: ansible-galaxy install -r requirements/common.yaml

      - name: Lint
        run: ansible-lint main.yaml
