---
- name: "Bat | Checking for Distribution Config | {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: bat_distribution_config

- name: "Bat | Run Tasks | {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: bat_distribution_config.stat.exists

- name: "Bat | Update Bat Cache | {{ ansible_distribution }}"
  ansible.builtin.command:
    cmd: bat cache --build
  register: bat_cache
  changed_when: bat_cache.rc != 0
